import Head from 'next/head'
import { Inter } from '@next/font/google'
import HomeLayout from './shared/home'
import HeaderLayout from './shared/header'
import SidebarLayout from './shared/sidebar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>NueroLearn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
    <div>
      <HeaderLayout></HeaderLayout>
      <HomeLayout></HomeLayout>
    </div>

    </>
  )
}
